[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/proof-core",
]
exclude = [
    "projects/.DS_Store",
    "projects/sum100-ts",
    "projects/sum100-h5",
]

[profile.release]
lto = true
panic = "abort"
